version: '3'
services:
  spring-boot-app:
    image: spring-boot-app
    build: .
    ports:
      - 8000-8999:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
